# Generated by Django 5.0.7 on 2024-10-24 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Tax', 'verbose_name_plural': 'Taxes'},
        ),
    ]
